name: Update JSON File

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
jobs:

  update-json:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout 
      uses: actions/checkout@v4

    - name: Update JSON file
      run:  |
        echo "remove subtopics.json"
        rm -f ./subtopics.json
        bash ./update.sh

      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update subtopics.json"
        git push origin main